# Generated by Django 5.0.6 on 2024-06-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_team_alter_about_img_alter_banner_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/feedback/customer')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('feedback', models.CharField(max_length=500)),
            ],
        ),
    ]
